databaseChangeLog:
  - changeSet:
      id: 007-environment
      author: freezehub
      changes:
        - createTable:
            tableName: environment
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: organization_id
                  type: bigint
                  constraints:
                    nullable: false
                    references: organization(id)
                    foreignKeyName: fk_environment_organization
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamptz
                  defaultValueComputed: now()
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamptz
                  defaultValueComputed: now()
                  constraints:
                    nullable: false
        - addUniqueConstraint:
            tableName: environment
            columnNames: organization_id, name
            constraintName: uq_environment_organization_name
